/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.jdbc;

import market.dao.*;
import market.factory.*;
import java.util.Date;
import market.dto.*;
import market.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CartDaoImpl extends AbstractDAO implements CartDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT account_id, line_item_id, qty, created FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( account_id, line_item_id, qty, created ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET qty = ?, created = ? WHERE account_id = ? AND line_item_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE account_id = ? AND line_item_id = ?";

	/** 
	 * Index of column account_id
	 */
	protected static final int COLUMN_ACCOUNT_ID = 1;

	/** 
	 * Index of column line_item_id
	 */
	protected static final int COLUMN_LINE_ITEM_ID = 2;

	/** 
	 * Index of column qty
	 */
	protected static final int COLUMN_QTY = 3;

	/** 
	 * Index of column created
	 */
	protected static final int COLUMN_CREATED = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column account_id
	 */
	protected static final int PK_COLUMN_ACCOUNT_ID = 1;

	/** 
	 * Index of primary-key column line_item_id
	 */
	protected static final int PK_COLUMN_LINE_ITEM_ID = 2;

	/** 
	 * Inserts a new row in the Cart table.
	 */
	public CartPk insert(Cart dto) throws CartDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getAccountId() );
			stmt.setInt( index++, dto.getLineItemId() );
			stmt.setInt( index++, dto.getQty() );
			stmt.setTimestamp(index++, dto.getCreated()==null ? null : new java.sql.Timestamp( dto.getCreated().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CartDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the Cart table.
	 */
	public void update(Cart dto) throws CartDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			//stmt.setInt( index++, dto.getAccountId() );
			//stmt.setInt( index++, dto.getLineItemId() );
			stmt.setInt( index++, dto.getQty() );
			stmt.setTimestamp(index++, dto.getCreated()==null ? null : new java.sql.Timestamp( dto.getCreated().getTime() ) );
			stmt.setInt( 3, dto.getAccountId() );
			stmt.setInt( 4, dto.getLineItemId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CartDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the Cart table.
	 */
	public void delete(CartPk pk) throws CartDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getAccountId() );
			stmt.setInt( 2, pk.getLineItemId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CartDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the Cart table that matches the specified primary-key value.
	 */
	public Cart findByPrimaryKey(CartPk pk) throws CartDaoException
	{
		return findByPrimaryKey( pk.getAccountId(), pk.getLineItemId() );
	}

	/** 
	 * Returns all rows from the Cart table that match the criteria 'account_id = :accountId AND line_item_id = :lineItemId'.
	 */
	public Cart findByPrimaryKey(int accountId, int lineItemId) throws CartDaoException
	{
		Cart ret[] = findByDynamicSelect( SQL_SELECT + " WHERE account_id = ? AND line_item_id = ?", new Object[] {  new Integer(accountId),  new Integer(lineItemId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the Cart table that match the criteria ''.
	 */
	public Cart[] findAll() throws CartDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}
	
	/** 
	 * Returns all rows from the Cart table that match the criteria ''.
	 */
	public Cart[] findAll(int accountId) throws CartDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE account_id = ?  ", new Object[] {  new Integer(accountId)  } );
	}

	/**
	 * Method 'CartDaoImpl'
	 * 
	 */
	public CartDaoImpl()
	{
	}

	/**
	 * Method 'CartDaoImpl'
	 * 
	 * @param userConn
	 */
	public CartDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "Cart";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Cart fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Cart dto = new Cart();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Cart[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Cart dto = new Cart();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Cart ret[] = new Cart[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Cart dto, ResultSet rs) throws SQLException
	{
		dto.setAccountId( rs.getInt( COLUMN_ACCOUNT_ID ) );
		dto.setLineItemId( rs.getInt( COLUMN_LINE_ITEM_ID ) );
		dto.setQty( rs.getInt( COLUMN_QTY ) );
		dto.setCreated( rs.getTimestamp(COLUMN_CREATED ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Cart dto)
	{
	}

	/** 
	 * Returns all rows from the Cart table that match the specified arbitrary SQL statement
	 */
	public Cart[] findByDynamicSelect(String sql, Object[] sqlParams) throws CartDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CartDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the Cart table that match the specified arbitrary SQL statement
	 */
	public Cart[] findByDynamicWhere(String sql, Object[] sqlParams) throws CartDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CartDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
