/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.dto;

import market.dao.*;
import market.factory.*;
import market.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Account implements Serializable
{
	/** 
	 * This attribute maps to the column id in the Account table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column address_id in the Account table.
	 */
	protected int addressId;

	/** 
	 * This attribute maps to the column isClosed in the Account table.
	 */
	protected boolean isClosed;

	/** 
	 * This attribute maps to the column open in the Account table.
	 */
	protected Date open;

	/** 
	 * This attribute maps to the column closed in the Account table.
	 */
	protected Date closed;

	/**
	 * Method 'Account'
	 * 
	 */
	public Account()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getAddressId'
	 * 
	 * @return int
	 */
	public int getAddressId()
	{
		return addressId;
	}

	/**
	 * Method 'setAddressId'
	 * 
	 * @param addressId
	 */
	public void setAddressId(int addressId)
	{
		this.addressId = addressId;
	}

	/**
	 * Method 'isIsClosed'
	 * 
	 * @return boolean
	 */
	public boolean isIsClosed()
	{
		return isClosed;
	}

	/**
	 * Method 'setIsClosed'
	 * 
	 * @param isClosed
	 */
	public void setIsClosed(boolean isClosed)
	{
		this.isClosed = isClosed;
	}

	/**
	 * Method 'getOpen'
	 * 
	 * @return Date
	 */
	public Date getOpen()
	{
		return open;
	}

	/**
	 * Method 'setOpen'
	 * 
	 * @param open
	 */
	public void setOpen(Date open)
	{
		this.open = open;
	}

	/**
	 * Method 'getClosed'
	 * 
	 * @return Date
	 */
	public Date getClosed()
	{
		return closed;
	}

	/**
	 * Method 'setClosed'
	 * 
	 * @param closed
	 */
	public void setClosed(Date closed)
	{
		this.closed = closed;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Account)) {
			return false;
		}
		
		final Account _cast = (Account) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (addressId != _cast.addressId) {
			return false;
		}
		
		if (isClosed != _cast.isClosed) {
			return false;
		}
		
		if (open == null ? _cast.open != open : !open.equals( _cast.open )) {
			return false;
		}
		
		if (closed == null ? _cast.closed != closed : !closed.equals( _cast.closed )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + addressId;
		_hashCode = 29 * _hashCode + (isClosed ? 1 : 0);
		if (open != null) {
			_hashCode = 29 * _hashCode + open.hashCode();
		}
		
		if (closed != null) {
			_hashCode = 29 * _hashCode + closed.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AccountPk
	 */
	public AccountPk createPk()
	{
		return new AccountPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "market.dto.Account: " );
		ret.append( "id=" + id );
		ret.append( ", addressId=" + addressId );
		ret.append( ", isClosed=" + isClosed );
		ret.append( ", open=" + open );
		ret.append( ", closed=" + closed );
		return ret.toString();
	}

}
