/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.dto;

import market.dao.*;
import market.factory.*;
import market.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Cart implements Serializable
{
	/** 
	 * This attribute maps to the column account_id in the Cart table.
	 */
	protected int accountId;

	/** 
	 * This attribute maps to the column line_item_id in the Cart table.
	 */
	protected int lineItemId;

	/** 
	 * This attribute maps to the column qty in the Cart table.
	 */
	protected int qty;

	/** 
	 * This attribute maps to the column created in the Cart table.
	 */
	protected Date created;

	/**
	 * Method 'Cart'
	 * 
	 */
	public Cart()
	{
	}

	/**
	 * Method 'getAccountId'
	 * 
	 * @return int
	 */
	public int getAccountId()
	{
		return accountId;
	}

	/**
	 * Method 'setAccountId'
	 * 
	 * @param accountId
	 */
	public void setAccountId(int accountId)
	{
		this.accountId = accountId;
	}

	/**
	 * Method 'getLineItemId'
	 * 
	 * @return int
	 */
	public int getLineItemId()
	{
		return lineItemId;
	}

	/**
	 * Method 'setLineItemId'
	 * 
	 * @param lineItemId
	 */
	public void setLineItemId(int lineItemId)
	{
		this.lineItemId = lineItemId;
	}

	/**
	 * Method 'getQty'
	 * 
	 * @return int
	 */
	public int getQty()
	{
		return qty;
	}

	/**
	 * Method 'setQty'
	 * 
	 * @param qty
	 */
	public void setQty(int qty)
	{
		this.qty = qty;
	}

	/**
	 * Method 'getCreated'
	 * 
	 * @return Date
	 */
	public Date getCreated()
	{
		return created;
	}

	/**
	 * Method 'setCreated'
	 * 
	 * @param created
	 */
	public void setCreated(Date created)
	{
		this.created = created;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cart)) {
			return false;
		}
		
		final Cart _cast = (Cart) _other;
		if (accountId != _cast.accountId) {
			return false;
		}
		
		if (lineItemId != _cast.lineItemId) {
			return false;
		}
		
		if (qty != _cast.qty) {
			return false;
		}
		
		if (created == null ? _cast.created != created : !created.equals( _cast.created )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + accountId;
		_hashCode = 29 * _hashCode + lineItemId;
		_hashCode = 29 * _hashCode + qty;
		if (created != null) {
			_hashCode = 29 * _hashCode + created.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CartPk
	 */
	public CartPk createPk()
	{
		return new CartPk(accountId, lineItemId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "market.dto.Cart: " );
		ret.append( "accountId=" + accountId );
		ret.append( ", lineItemId=" + lineItemId );
		ret.append( ", qty=" + qty );
		ret.append( ", created=" + created );
		return ret.toString();
	}

}
