/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.dto;

import market.dao.*;
import market.factory.*;
import market.exceptions.*;

import java.io.Serializable;
import java.util.*;

public class Customer implements Serializable
{
	/** 
	 * This attribute maps to the column id in the Customer table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column firstName in the Customer table.
	 */
	protected String firstName;

	/** 
	 * This attribute maps to the column LastName in the Customer table.
	 */
	protected String lastName;

	/** 
	 * This attribute maps to the column email in the Customer table.
	 */
	protected String email;

	/** 
	 * This attribute maps to the column state in the Customer table.
	 */
	protected int state;

	/** 
	 * This attribute maps to the column lastLogin in the Customer table.
	 */
	protected Date lastLogin;

	/** 
	 * This attribute maps to the column password in the Customer table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column userName in the Customer table.
	 */
	protected String userName;
	protected int accountId;
	

	/**
	 * Method 'Customer'
	 * 
	 */
	public Customer()
	{
	}

	public int getAccountId() {
		return accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getFirstName'
	 * 
	 * @return String
	 */
	public String getFirstName()
	{
		return firstName;
	}

	/**
	 * Method 'setFirstName'
	 * 
	 * @param firstName
	 */
	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	/**
	 * Method 'getLastName'
	 * 
	 * @return String
	 */
	public String getLastName()
	{
		return lastName;
	}

	/**
	 * Method 'setLastName'
	 * 
	 * @param lastName
	 */
	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * Method 'getState'
	 * 
	 * @return int
	 */
	public int getState()
	{
		return state;
	}

	/**
	 * Method 'setState'
	 * 
	 * @param state
	 */
	public void setState(int state)
	{
		this.state = state;
	}

	/**
	 * Method 'getLastLogin'
	 * 
	 * @return Date
	 */
	public Date getLastLogin()
	{
		return lastLogin;
	}

	/**
	 * Method 'setLastLogin'
	 * 
	 * @param lastLogin
	 */
	public void setLastLogin(Date lastLogin)
	{
		this.lastLogin = lastLogin;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getUserName'
	 * 
	 * @return String
	 */
	public String getUserName()
	{
		return userName;
	}

	/**
	 * Method 'setUserName'
	 * 
	 * @param userName
	 */
	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Customer)) {
			return false;
		}
		
		final Customer _cast = (Customer) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (firstName == null ? _cast.firstName != firstName : !firstName.equals( _cast.firstName )) {
			return false;
		}
		
		if (lastName == null ? _cast.lastName != lastName : !lastName.equals( _cast.lastName )) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (state != _cast.state) {
			return false;
		}
		
		if (lastLogin == null ? _cast.lastLogin != lastLogin : !lastLogin.equals( _cast.lastLogin )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (userName == null ? _cast.userName != userName : !userName.equals( _cast.userName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (firstName != null) {
			_hashCode = 29 * _hashCode + firstName.hashCode();
		}
		
		if (lastName != null) {
			_hashCode = 29 * _hashCode + lastName.hashCode();
		}
		
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		_hashCode = 29 * _hashCode + state;
		if (lastLogin != null) {
			_hashCode = 29 * _hashCode + lastLogin.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		if (userName != null) {
			_hashCode = 29 * _hashCode + userName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CustomerPk
	 */
	public CustomerPk createPk()
	{
		return new CustomerPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "market.dto.Customer: " );
		ret.append( "id=" + id );
		ret.append( ", firstName=" + firstName );
		ret.append( ", lastName=" + lastName );
		ret.append( ", email=" + email );
		ret.append( ", state=" + state );
		ret.append( ", lastLogin=" + lastLogin );
		ret.append( ", password=" + password );
		ret.append( ", userName=" + userName );
		return ret.toString();
	}
	
	public Cart getCart(){
		
		CartDao c_dao = CartDaoFactory.create();	
		
		
		
		try {
			c_dao.findAll(accountId);
		} catch (CartDaoException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		
		return null;
		
		
		
	}

}
