/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.dto;

import market.dao.*;
import market.factory.*;
import market.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class LineItem implements Serializable
{
	/** 
	 * This attribute maps to the column id in the LineItem table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column quantity in the LineItem table.
	 */
	protected int quantity;

	/** 
	 * This attribute maps to the column price in the LineItem table.
	 */
	protected Double price;

	/** 
	 * This attribute maps to the column product_id in the LineItem table.
	 */
	protected int productId;

	/** 
	 * This attribute maps to the column seller_id in the LineItem table.
	 */
	protected int sellerId;

	/** 
	 * This attribute maps to the column seller_info in the LineItem table.
	 */
	protected String sellerInfo;

	/**
	 * Method 'LineItem'
	 * 
	 */
	public LineItem()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getQuantity'
	 * 
	 * @return int
	 */
	public int getQuantity()
	{
		return quantity;
	}

	/**
	 * Method 'setQuantity'
	 * 
	 * @param quantity
	 */
	public void setQuantity(int quantity)
	{
		this.quantity = quantity;
	}

	/**
	 * Method 'getPrice'
	 * 
	 * @return Double
	 */
	public Double getPrice()
	{
		return price;
	}

	/**
	 * Method 'setPrice'
	 * 
	 * @param price
	 */
	public void setPrice(Double price)
	{
		this.price = price;
	}

	/**
	 * Method 'getProductId'
	 * 
	 * @return int
	 */
	public int getProductId()
	{
		return productId;
	}

	/**
	 * Method 'setProductId'
	 * 
	 * @param productId
	 */
	public void setProductId(int productId)
	{
		this.productId = productId;
	}

	/**
	 * Method 'getSellerId'
	 * 
	 * @return int
	 */
	public int getSellerId()
	{
		return sellerId;
	}

	/**
	 * Method 'setSellerId'
	 * 
	 * @param sellerId
	 */
	public void setSellerId(int sellerId)
	{
		this.sellerId = sellerId;
	}

	/**
	 * Method 'getSellerInfo'
	 * 
	 * @return String
	 */
	public String getSellerInfo()
	{
		return sellerInfo;
	}

	/**
	 * Method 'setSellerInfo'
	 * 
	 * @param sellerInfo
	 */
	public void setSellerInfo(String sellerInfo)
	{
		this.sellerInfo = sellerInfo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LineItem)) {
			return false;
		}
		
		final LineItem _cast = (LineItem) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (quantity != _cast.quantity) {
			return false;
		}
		
		if (price == null ? _cast.price != price : !price.equals( _cast.price )) {
			return false;
		}
		
		if (productId != _cast.productId) {
			return false;
		}
		
		if (sellerId != _cast.sellerId) {
			return false;
		}
		
		if (sellerInfo == null ? _cast.sellerInfo != sellerInfo : !sellerInfo.equals( _cast.sellerInfo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + quantity;
		if (price != null) {
			_hashCode = 29 * _hashCode + price.hashCode();
		}
		
		_hashCode = 29 * _hashCode + productId;
		_hashCode = 29 * _hashCode + sellerId;
		if (sellerInfo != null) {
			_hashCode = 29 * _hashCode + sellerInfo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return LineItemPk
	 */
	public LineItemPk createPk()
	{
		return new LineItemPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "market.dto.LineItem: " );
		ret.append( "id=" + id );
		ret.append( ", quantity=" + quantity );
		ret.append( ", price=" + price );
		ret.append( ", productId=" + productId );
		ret.append( ", sellerId=" + sellerId );
		ret.append( ", sellerInfo=" + sellerInfo );
		return ret.toString();
	}

}
