/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.dao;

import market.dto.*;
import market.exceptions.*;

public interface CustomerDao
{
	/** 
	 * Inserts a new row in the Customer table.
	 */
	public CustomerPk insert(Customer dto) throws CustomerDaoException;

	/** 
	 * Updates a single row in the Customer table.
	 */
	public void update(Customer dto) throws CustomerDaoException;

	/** 
	 * Deletes a single row in the Customer table.
	 */
	public void delete(CustomerPk pk) throws CustomerDaoException;

	/** 
	 * Returns the rows from the Customer table that matches the specified primary-key value.
	 */
	public Customer findByPrimaryKey(CustomerPk pk) throws CustomerDaoException;

	/** 
	 * Returns all rows from the Customer table that match the criteria 'id = :id'.
	 */
	public Customer findByPrimaryKey(int id) throws CustomerDaoException;

	/** 
	 * Returns all rows from the Customer table that match the criteria ''.
	 */
	public Customer[] findAll() throws CustomerDaoException;

	/** 
	 * Returns all rows from the Customer table that match the criteria ''.
	 */
	public Customer findByUserName(String userName) throws CustomerDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the Customer table that match the specified arbitrary SQL statement
	 */
	public Customer[] findByDynamicSelect(String sql, Object[] sqlParams) throws CustomerDaoException;

	/** 
	 * Returns all rows from the Customer table that match the specified arbitrary SQL statement
	 */
	public Customer[] findByDynamicWhere(String sql, Object[] sqlParams) throws CustomerDaoException;

	 

}
