/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.dao;

import market.dto.*;
import market.exceptions.*;

public interface ProductDao
{
	/** 
	 * Inserts a new row in the Product table.
	 */
	public ProductPk insert(Product dto) throws ProductDaoException;

	/** 
	 * Updates a single row in the Product table.
	 */
	public void update(ProductPk pk, Product dto) throws ProductDaoException;

	/** 
	 * Deletes a single row in the Product table.
	 */
	public void delete(ProductPk pk) throws ProductDaoException;

	/** 
	 * Returns the rows from the Product table that matches the specified primary-key value.
	 */
	public Product findByPrimaryKey(ProductPk pk) throws ProductDaoException;

	/** 
	 * Returns all rows from the Product table that match the criteria 'id = :id'.
	 */
	public Product findByPrimaryKey(int id) throws ProductDaoException;

	/** 
	 * Returns all rows from the Product table that match the criteria ''.
	 */
	public Product[] findAll() throws ProductDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the Product table that match the specified arbitrary SQL statement
	 */
	public Product[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProductDaoException;

	/** 
	 * Returns all rows from the Product table that match the specified arbitrary SQL statement
	 */
	public Product[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProductDaoException;

}
