/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.factory;

import java.sql.Connection;
import market.dao.*;
import market.jdbc.*;

public class AccountDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return AccountDao
	 */
	public static AccountDao create()
	{
		return new AccountDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return AccountDao
	 */
	public static AccountDao create(Connection conn)
	{
		return new AccountDaoImpl( conn );
	}

}
