/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.factory;

import java.sql.Connection;

import market.dao.CustomerDao;
import market.jdbc.*;

public class CustomerDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return CustomerDao
	 */
	public static CustomerDao create()
	{
		return new CustomerDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return CustomerDao
	 */
	public static CustomerDao create(Connection conn)
	{
		return new CustomerDaoImpl( conn );
	}

}
