/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package market.factory;

import java.sql.Connection;
import market.dao.*;
import market.jdbc.*;

public class LineItemDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return LineItemDao
	 */
	public static LineItemDao create()
	{
		return new LineItemDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return LineItemDao
	 */
	public static LineItemDao create(Connection conn)
	{
		return new LineItemDaoImpl( conn );
	}

}
